
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Jordy
 */
public class programJava_4 extends javax.swing.JFrame {

    /**
     * Creates new form programJava_4
     */
    public String nama = "";
    public String username ;
    public String password ;
    
    String jenKel;
    String nim;
    String tempatLahir;
    List<String> tanggalLahir = new ArrayList<>();
    String agama;
    String alamatAsal;
    String alamatDomisili;
    String foto;
    
    List<String> org_nama = new ArrayList<>();
    List<String> org_jabatan = new ArrayList<>();
    List<String> org_tahunMulai = new ArrayList<>();
    List<String> org_tahunSelesai = new ArrayList<>();
    
    List<String> kep_nama = new ArrayList<>();
    List<String> kep_jabatan = new ArrayList<>();
    List<String> kep_tahunMulai = new ArrayList<>();
    List<String> kep_tahunSelesai = new ArrayList<>();
    
    List<String> pen = new ArrayList<>();
    
    List<String> pres = new ArrayList<>();
    
    public programJava_4() {
        initComponents();
        jButtonSaveLogout.setEnabled(false);
    }

    public programJava_4(String nama, String username, String password) {
        initComponents();
        this.nama = nama;
        this.username = username;
        this.password = password;
        jLabelWelcome.setText("Selamat Datang, " + this.nama);
        jLabelNama.setText(this.nama);
        jLabelUsername.setText("username : "+this.username);
        jButtonSaveLogout.setEnabled(false);
    }
    
    private void org_updateDataTersimpan(){
        jLabelOrgDataTersimpan.setText("Data Tersimpan = "+ org_nama.size());
    }
    
    private void kep_updateDataTersimpan(){
        jLabelKepDataTersimpan.setText("Data Tersimpan = "+ kep_nama.size());
    }
    
    private void pen_updateDataTersimpan(){
        jLabelPenDataTersimpan.setText("Data Tersimpan = "+ pen.size());
    }
    
    private void pres_updateDataTersimpan(){
        jLabelPresDataTersimpan.setText("Data Tersimpan = "+ pres.size());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJenKel = new javax.swing.ButtonGroup();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jRadioButtonL = new javax.swing.JRadioButton();
        jRadioButtonP = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTempatLahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTanggalLahir = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxBulanLahir = new javax.swing.JComboBox<>();
        jTextFieldTahunLahir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxAgama = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldOrgNama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldOrgJabatan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldOrgTahunSelesai = new javax.swing.JTextField();
        jTextFieldOrgTahunMulai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonOrgAdd = new javax.swing.JButton();
        jButtonOrgReset = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldAlamatDomisili = new javax.swing.JTextField();
        jTextFieldAlamatAsal = new javax.swing.JTextField();
        jLabelOrgDataTersimpan = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButtonKepAdd = new javax.swing.JButton();
        jButtonKepReset = new javax.swing.JButton();
        jLabelKepDataTersimpan = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldKepNama = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldKepJabatan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldKepTahunSelesai = new javax.swing.JTextField();
        jTextFieldKepTahunMulai = new javax.swing.JTextField();
        jButtonSaveLogout = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldPen = new javax.swing.JTextField();
        jButtonPenAdd = new javax.swing.JButton();
        jButtonPenReset = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldPres = new javax.swing.JTextField();
        jButtonPresAdd = new javax.swing.JButton();
        jButtonPresReset = new javax.swing.JButton();
        jLabelPenDataTersimpan = new javax.swing.JLabel();
        jLabelPresDataTersimpan = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jCheckBoxDataBenar = new javax.swing.JCheckBox();
        jButtonUnggahFoto = new javax.swing.JButton();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldFoto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Template CV Terbaik");
        setIconImages(null);
        setLocation(new java.awt.Point(150, 0));
        setPreferredSize(new java.awt.Dimension(850, 710));
        setResizable(false);

        jLabelWelcome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelWelcome.setText("Selamat datang, ...");
        jLabelWelcome.setToolTipText("");

        jLabelUsername.setText("username : ");

        jLabel2.setText("Nama :");

        jLabel3.setText("Jenis Kelamin :");

        jLabelNama.setText("nama");

        buttonGroupJenKel.add(jRadioButtonL);
        jRadioButtonL.setText("Laki-laki");

        buttonGroupJenKel.add(jRadioButtonP);
        jRadioButtonP.setText("Perempuan");

        jLabel4.setText("NIM :");

        jLabel5.setText("Tempat :");

        jTextFieldTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTempatLahirActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Lahir :");

        jComboBoxTanggalLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTanggalLahirActionPerformed(evt);
            }
        });

        jLabel7.setText("     DD                  MM            YYYY");

        jComboBoxBulanLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBoxBulanLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBulanLahirActionPerformed(evt);
            }
        });

        jLabel8.setText("Agama :");

        jComboBoxAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kristen", "Islam", "Katolik", "Hindu", "Buddha", "Kong Hu Cu" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("PROFIL");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PENGALAMAN ORGANISASI");

        jLabel11.setText("Nama Organisasi :");

        jLabel12.setText("Jabatan :");

        jLabel13.setText("Tahun :");

        jLabel14.setText("s/d");

        jButtonOrgAdd.setText("Add Data..");
        jButtonOrgAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrgAddActionPerformed(evt);
            }
        });

        jButtonOrgReset.setText("Reset Data..");
        jButtonOrgReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrgResetActionPerformed(evt);
            }
        });

        jLabel15.setText("Alamat Asal :");

        jLabel16.setText("Alamat Domisili :");

        jLabelOrgDataTersimpan.setText("Data Tersimpan = 0");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("PENGALAMAN KEPANITIAAN");

        jLabel19.setText("s/d");

        jButtonKepAdd.setText("Add Data..");
        jButtonKepAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKepAddActionPerformed(evt);
            }
        });

        jButtonKepReset.setText("Reset Data..");
        jButtonKepReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKepResetActionPerformed(evt);
            }
        });

        jLabelKepDataTersimpan.setText("Data Tersimpan = 0");

        jLabel21.setText("Nama Kepanitiaan :");

        jLabel22.setText("Jabatan :");

        jLabel23.setText("Tahun :");

        jButtonSaveLogout.setText("Save Data & Logout..");
        jButtonSaveLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveLogoutActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("RIWAYAT PENDIDIKAN");

        jButtonPenAdd.setText("Add Data..");
        jButtonPenAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPenAddActionPerformed(evt);
            }
        });

        jButtonPenReset.setText("Reset Data..");
        jButtonPenReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPenResetActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("RIWAYAT PRESTASI");

        jButtonPresAdd.setText("Add Data..");
        jButtonPresAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPresAddActionPerformed(evt);
            }
        });

        jButtonPresReset.setText("Reset Data..");
        jButtonPresReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPresResetActionPerformed(evt);
            }
        });

        jLabelPenDataTersimpan.setText("Data Tersimpan = 0");

        jLabelPresDataTersimpan.setText("Data Tersimpan = 0");

        jCheckBoxDataBenar.setText("Semua data input sudah benar adanya");
        jCheckBoxDataBenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDataBenarActionPerformed(evt);
            }
        });

        jButtonUnggahFoto.setText("Unggah foto..");
        jButtonUnggahFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnggahFotoActionPerformed(evt);
            }
        });

        jLabelFoto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelFoto.setIconTextGap(100);
        jLabelFoto.setMaximumSize(new java.awt.Dimension(140, 169));
        jLabelFoto.setMinimumSize(new java.awt.Dimension(140, 169));
        jLabelFoto.setPreferredSize(new java.awt.Dimension(140, 169));

        jTextFieldFoto.setText("ukuran : 140x169");
        jTextFieldFoto.setMaximumSize(new java.awt.Dimension(6, 20));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                        .addComponent(jLabelUsername)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldAlamatAsal)
                                        .addComponent(jTextFieldAlamatDomisili, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonUnggahFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(17, 17, 17))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                            .addComponent(jLabel7)
                                            .addGap(20, 20, 20))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel2))
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(63, 63, 63)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(16, 16, 16)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextFieldTempatLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldNim)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(15, 15, 15)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabelNama)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jRadioButtonL)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jRadioButtonP))))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jComboBoxTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxBulanLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldTahunLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelPenDataTersimpan)
                                        .addComponent(jLabelPresDataTersimpan)
                                        .addComponent(jTextFieldPres, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPen))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonPenAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonPenReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonPresReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonPresAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel25)))
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldOrgNama)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldOrgTahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldOrgTahunSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextFieldOrgJabatan)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxDataBenar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonOrgAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonOrgReset, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldKepTahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldKepTahunSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextFieldKepNama)
                                            .addComponent(jTextFieldKepJabatan, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelKepDataTersimpan, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelOrgDataTersimpan, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButtonSaveLogout)
                                                .addGap(19, 19, 19))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonKepAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jButtonKepReset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelWelcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelOrgDataTersimpan)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextFieldOrgNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextFieldOrgJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextFieldOrgTahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldOrgTahunSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonOrgAdd)
                                    .addComponent(jButtonOrgReset))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelKepDataTersimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jTextFieldKepNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jTextFieldKepJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jTextFieldKepTahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldKepTahunSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonKepAdd)
                                    .addComponent(jButtonKepReset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jRadioButtonL)
                                            .addComponent(jRadioButtonP))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(jTextFieldNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jTextFieldTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldTahunLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxBulanLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jTextFieldFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButtonUnggahFoto))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jTextFieldAlamatAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldAlamatDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPenAdd)
                                    .addComponent(jLabelPenDataTersimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPenReset)
                                    .addComponent(jTextFieldPen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPresDataTersimpan)
                                    .addComponent(jButtonPresAdd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonPresReset)
                                    .addComponent(jTextFieldPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxDataBenar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSaveLogout))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTempatLahirActionPerformed

    private void jButtonUnggahFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnggahFotoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        ImageIcon im = new ImageIcon(f.toString());
        jLabelFoto.setIcon(im);
        jLabelFoto.setSize(140, 169);
        jTextFieldFoto.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButtonUnggahFotoActionPerformed

    private void jComboBoxTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTanggalLahirActionPerformed

    private void jComboBoxBulanLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBulanLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBulanLahirActionPerformed

    private void jCheckBoxDataBenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDataBenarActionPerformed
        // TODO add your handling code here:
   
        if(jCheckBoxDataBenar.isSelected()) {
            jButtonSaveLogout.setEnabled(true);
        } else {
            jButtonSaveLogout.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxDataBenarActionPerformed

    private void jButtonSaveLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveLogoutActionPerformed
        // TODO add your handling code here:
        if(jTextFieldNim.getText().equals("") || jTextFieldTempatLahir.getText().equals("") || 
            jTextFieldAlamatAsal.getText().equals("") || jTextFieldAlamatDomisili.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Lengkapi profil Anda terlebih dahulu!","Warning", HEIGHT);
        } else {
            //jenis kelamin
            if(jRadioButtonL.isSelected()) {
                jenKel = "Laki-laki";
            } else if (jRadioButtonP.isSelected()){
                jenKel = "Perempuan";
            }
            //NIM
            nim = jTextFieldNim.getText();
            //Tempat dan Tanggal Lahir
            tempatLahir = jTextFieldTempatLahir.getText();
                tanggalLahir.add(jComboBoxTanggalLahir.getSelectedItem().toString());
                switch(jComboBoxBulanLahir.getSelectedItem().toString()){
                    case "01": tanggalLahir.add("Januari"); break;
                    case "02": tanggalLahir.add("Februari"); break;
                    case "03": tanggalLahir.add("Maret"); break;
                    case "04": tanggalLahir.add("April"); break;
                    case "05": tanggalLahir.add("Mei"); break;
                    case "06": tanggalLahir.add("Juni"); break;
                    case "07": tanggalLahir.add("Juli"); break;
                    case "08": tanggalLahir.add("Agustus"); break;
                    case "09": tanggalLahir.add("September"); break;
                    case "10": tanggalLahir.add("Oktober"); break;
                    case "11": tanggalLahir.add("November"); break;
                    case "12": tanggalLahir.add("Desember"); break;
                }
                tanggalLahir.add(jTextFieldTahunLahir.getText());
            //Agama dan Alamat
            agama = jComboBoxAgama.getSelectedItem().toString();
            alamatAsal = jTextFieldAlamatAsal.getText();
            alamatDomisili = jTextFieldAlamatDomisili.getText();
            //foto
            foto = jTextFieldFoto.getText();
            
            Profil Prof = new Profil(nama, jenKel, nim, tempatLahir, tanggalLahir, agama, alamatAsal, alamatDomisili, foto);
            Organisasi Org = new Organisasi(org_nama, org_jabatan, org_tahunMulai, org_tahunSelesai);
            Kepanitiaan Kep = new Kepanitiaan(kep_nama, kep_jabatan, kep_tahunMulai, kep_tahunSelesai);
            Pendidikan Pen = new Pendidikan(pen);
            Prestasi Pres = new Prestasi(pres);

            this.dispose();
            new programJava(Prof,Org,Kep,Pen,Pres).setVisible(true);
        }
    }//GEN-LAST:event_jButtonSaveLogoutActionPerformed

    private void jButtonOrgAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrgAddActionPerformed
        // TODO add your handling code here:
        String n = jTextFieldOrgNama.getText();
        String j = jTextFieldOrgJabatan.getText();
        String tm = jTextFieldOrgTahunMulai.getText();
        String ts = jTextFieldOrgTahunSelesai.getText();
        
        if(n.equals("") || j.equals("") || tm.equals("") || ts.equals("")) {
            JOptionPane.showMessageDialog(this, "Data organisasi tidak lengkap!", "Warning", HEIGHT);
        } else {
            org_nama.add(n);
            org_jabatan.add(j);
            org_tahunMulai.add(tm);
            org_tahunSelesai.add(ts);
            org_updateDataTersimpan();

            jTextFieldOrgNama.setText("");
            jTextFieldOrgJabatan.setText("");
            jTextFieldOrgTahunMulai.setText("");
            jTextFieldOrgTahunSelesai.setText("");
        }
    }//GEN-LAST:event_jButtonOrgAddActionPerformed

    private void jButtonOrgResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrgResetActionPerformed
        // TODO add your handling code here:
        jTextFieldOrgNama.setText("");
        jTextFieldOrgJabatan.setText("");
        jTextFieldOrgTahunMulai.setText("");
        jTextFieldOrgTahunSelesai.setText("");
        
        org_nama.clear();
        org_jabatan.clear();
        org_tahunMulai.clear();
        org_tahunSelesai.clear();
        
        org_updateDataTersimpan();
    }//GEN-LAST:event_jButtonOrgResetActionPerformed

    private void jButtonKepAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKepAddActionPerformed
        // TODO add your handling code here:
        String n = jTextFieldKepNama.getText();
        String j = jTextFieldKepJabatan.getText();
        String tm = jTextFieldKepTahunMulai.getText();
        String ts = jTextFieldKepTahunSelesai.getText();
        
        if(n.equals("") || j.equals("") || tm.equals("") || ts.equals("")) {
            JOptionPane.showMessageDialog(this, "Data kepanitiaan tidak lengkap!", "Warning", HEIGHT);
        } else {
            kep_nama.add(n);
            kep_jabatan.add(j);
            kep_tahunMulai.add(tm);
            kep_tahunSelesai.add(ts);
            kep_updateDataTersimpan();

            jTextFieldKepNama.setText("");
            jTextFieldKepJabatan.setText("");
            jTextFieldKepTahunMulai.setText("");
            jTextFieldKepTahunSelesai.setText("");
        }
    }//GEN-LAST:event_jButtonKepAddActionPerformed

    private void jButtonKepResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKepResetActionPerformed
        // TODO add your handling code here:
        jTextFieldKepNama.setText("");
        jTextFieldKepJabatan.setText("");
        jTextFieldKepTahunMulai.setText("");
        jTextFieldKepTahunSelesai.setText("");
        
        kep_nama.clear();
        kep_jabatan.clear();
        kep_tahunMulai.clear();
        kep_tahunSelesai.clear();
        
        kep_updateDataTersimpan();
    }//GEN-LAST:event_jButtonKepResetActionPerformed

    private void jButtonPenAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPenAddActionPerformed
        // TODO add your handling code here:
        String p = jTextFieldPen.getText();
        
        if(p.equals("")) {
            JOptionPane.showMessageDialog(this, "Data pendidikan tidak lengkap!", "Warning", HEIGHT);
        } else {
            pen.add(p);
            pen_updateDataTersimpan();
            jTextFieldPen.setText("");
        }
    }//GEN-LAST:event_jButtonPenAddActionPerformed

    private void jButtonPenResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPenResetActionPerformed
        // TODO add your handling code here:
        jTextFieldPen.setText("");
        pen.clear();
        pen_updateDataTersimpan();
    }//GEN-LAST:event_jButtonPenResetActionPerformed

    private void jButtonPresAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPresAddActionPerformed
        // TODO add your handling code here:
        String p = jTextFieldPres.getText();
        
        if(p.equals("")) {
            JOptionPane.showMessageDialog(this, "Data prestasi tidak lengkap!", "Warning", HEIGHT);
        } else {
            pres.add(p);
            pres_updateDataTersimpan();
            jTextFieldPres.setText("");
        }
    }//GEN-LAST:event_jButtonPresAddActionPerformed

    private void jButtonPresResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPresResetActionPerformed
        // TODO add your handling code here:
        jTextFieldPres.setText("");
        pres.clear();
        pres_updateDataTersimpan();
    }//GEN-LAST:event_jButtonPresResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programJava_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programJava_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programJava_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programJava_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programJava_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJenKel;
    private javax.swing.JButton jButtonKepAdd;
    private javax.swing.JButton jButtonKepReset;
    private javax.swing.JButton jButtonOrgAdd;
    private javax.swing.JButton jButtonOrgReset;
    private javax.swing.JButton jButtonPenAdd;
    private javax.swing.JButton jButtonPenReset;
    private javax.swing.JButton jButtonPresAdd;
    private javax.swing.JButton jButtonPresReset;
    private javax.swing.JButton jButtonSaveLogout;
    private javax.swing.JButton jButtonUnggahFoto;
    private javax.swing.JCheckBox jCheckBoxDataBenar;
    private javax.swing.JComboBox<String> jComboBoxAgama;
    private javax.swing.JComboBox<String> jComboBoxBulanLahir;
    private javax.swing.JComboBox<String> jComboBoxTanggalLahir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelKepDataTersimpan;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelOrgDataTersimpan;
    private javax.swing.JLabel jLabelPenDataTersimpan;
    private javax.swing.JLabel jLabelPresDataTersimpan;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JRadioButton jRadioButtonL;
    private javax.swing.JRadioButton jRadioButtonP;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldAlamatAsal;
    private javax.swing.JTextField jTextFieldAlamatDomisili;
    private javax.swing.JTextField jTextFieldFoto;
    private javax.swing.JTextField jTextFieldKepJabatan;
    private javax.swing.JTextField jTextFieldKepNama;
    private javax.swing.JTextField jTextFieldKepTahunMulai;
    private javax.swing.JTextField jTextFieldKepTahunSelesai;
    private javax.swing.JTextField jTextFieldNim;
    private javax.swing.JTextField jTextFieldOrgJabatan;
    private javax.swing.JTextField jTextFieldOrgNama;
    private javax.swing.JTextField jTextFieldOrgTahunMulai;
    private javax.swing.JTextField jTextFieldOrgTahunSelesai;
    private javax.swing.JTextField jTextFieldPen;
    private javax.swing.JTextField jTextFieldPres;
    private javax.swing.JTextField jTextFieldTahunLahir;
    private javax.swing.JTextField jTextFieldTempatLahir;
    // End of variables declaration//GEN-END:variables
}
