/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.BadElementException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Image;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
/**
 *
 * @author Jordy
 */
public class programJava extends javax.swing.JFrame  {
    
    int n=0;
    public List<String> nama = new ArrayList<>();
    public List<String> username = new ArrayList<>();
    public List<String> password = new ArrayList<>();
    public Profil mProf;
    public Organisasi mOrg;
    public Kepanitiaan mKep;
    public Pendidikan mPen;
    public Prestasi mPres;
    
    Document document = new Document();
    PdfWriter writer = null;
    Image image = null;
    /**
     * Creates new form programJava
     */

    private void updateDataTersimpan() {
        jLabelDataTersimpan.setText("Data Tersimpan = "+nama.size());
    }
    
    public programJava() {
        initComponents();
        jButtonCetak.setEnabled(false);
    }

    public programJava(List<String> nama, List<String> username, List<String> password) {
        initComponents();
        this.nama = nama;
        this.username = username;
        this.password = password;
        updateDataTersimpan();
        jButtonCetak.setEnabled(false);
        jLabelSiapCetak.setText("Siap Cetak = "+n);
    }
    
    public programJava(Profil prof, Organisasi org, Kepanitiaan kep, Pendidikan pen, Prestasi pres) {
        initComponents();
        this.mProf = prof;
        this.mOrg = org;
        this.mKep = kep;
        this.mPen = pen;
        this.mPres = pres;
        updateDataTersimpan();
        jButtonCetak.setEnabled(true);
        n++;
        jLabelSiapCetak.setText("Siap Cetak = "+n);
        jLabelInstruksi.setText("Slilahkan klik 'Cetak' untuk membuat file pdf");
    }
    
    private boolean isUsername(List<String> us, String text){
       boolean found = false;
       for  (String object : us) {
           if(object.equals(text)) {
               found = true;
           }
       }
       return found;
    }
    
    public void input(String text, Font f, int alignment) throws DocumentException {
        Paragraph p = new Paragraph(text,f);
        p.setAlignment(alignment);
        document.add(p);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonLupaPassword = new javax.swing.JButton();
        jButtonSignUp = new javax.swing.JButton();
        jLabelDataTersimpan = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JPasswordField();
        jButtonCetak = new javax.swing.JButton();
        jLabelSiapCetak = new javax.swing.JLabel();
        jLabelInstruksi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CV Terbaik - Login");
        setLocation(new java.awt.Point(450, 200));
        setPreferredSize(new java.awt.Dimension(400, 320));
        setResizable(false);

        jLabel1.setText("username :");

        jLabel2.setText("password :");

        jButtonLogin.setText("Login..");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonLupaPassword.setText("Lupa Password?");
        jButtonLupaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLupaPasswordActionPerformed(evt);
            }
        });

        jButtonSignUp.setText("Sign Up..");
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });

        jLabelDataTersimpan.setText("Data Tersimpan = 0");

        jButtonCetak.setText("Cetak..");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });

        jLabelSiapCetak.setText("Siap Cetak = 0");

        jLabelInstruksi.setText("Silahkan klik \"Sign Up\" apabila belum memiliki akun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDataTersimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSiapCetak))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonLupaPassword)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInstruksi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelInstruksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataTersimpan)
                    .addComponent(jLabelSiapCetak))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLupaPassword)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSignUp)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonCetak))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        String u = jTextFieldUsername.getText();
        String p = jTextFieldPassword.getText();
        if(u.equals("") && p.equals("")) {
            JOptionPane.showMessageDialog(this, "Username atau password kosong","Warning",HEIGHT);
        } else {
            if(isUsername(username,u)) {
                int i = username.indexOf(u);
                if(password.get(i).equals(p)) {
                    this.dispose();
                    new programJava_4(nama.get(i), username.get(i), password.get(i)).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Password Salah","Warning",HEIGHT);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username tidak ada","Warning",HEIGHT);
            }
        }
        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new programJava_2(nama,username,password).setVisible(true);
        updateDataTersimpan();
    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void jButtonLupaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLupaPasswordActionPerformed
        // TODO add your handling code here:
        new programJava_3(nama, username, password).setVisible(true);
    }//GEN-LAST:event_jButtonLupaPasswordActionPerformed

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files","pdf");
        fc.setFileFilter(filter);
        fc.showSaveDialog(this);
        System.out.println("Nama foto : "+mProf.foto);
        String loc = fc.getSelectedFile().getAbsolutePath() + ".pdf";
        try{
            try {
                writer = PdfWriter.getInstance(document, new FileOutputStream(loc));
                image = Image.getInstance(mProf.foto);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(programJava.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BadElementException ex) {
                Logger.getLogger(programJava.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(programJava.class.getName()).log(Level.SEVERE, null, ex);
            }
            document.open();
                Font font1 = new Font();
                    font1.setStyle(Font.BOLD);
                    font1.setSize(25);
                Font font2 = new Font();
                    font2.setStyle(Font.NORMAL);
                    font2.setSize(15);
               
      
                input("CV Otomatis",font1,Element.ALIGN_CENTER);
                document.add(image);
                input("--------------------------------------------------------------------------------------------------------",font2,Element.ALIGN_JUSTIFIED);
                input("Nama Lengkap :  " +mProf.nama,font2,Element.ALIGN_LEFT);
                input("Jenis Kelamin   :  " +mProf.jenKel,font2,Element.ALIGN_LEFT);
                input("NIM                   :  " +mProf.nim,font2,Element.ALIGN_LEFT);
                input("Tempat             :  " +mProf.tempatLahir,font2,Element.ALIGN_LEFT);
                input("Tanggal Lahir   :  " +mProf.tanggalLahir.get(0)+" "+mProf.tanggalLahir.get(1)+
                        " "+mProf.tanggalLahir.get(2),font2,Element.ALIGN_LEFT);
                input("Agama              :  " +mProf.agama,font2,Element.ALIGN_LEFT);
                input("Alamat Asal      :  " +mProf.alamatAsal,font2,Element.ALIGN_LEFT);
                input("Alamat Domisili :  " +mProf.alamatDomisili,font2,Element.ALIGN_LEFT);
                input("--------------------------------------------------------------------------------------------------------",font2,Element.ALIGN_JUSTIFIED);
                input("PENGALAMAN ORGANISASI",font1,Element.ALIGN_CENTER);
                input(" ",font1,Element.ALIGN_CENTER);
                for (int i=0;i<mOrg.nama.size();i++) {
                    input((i+1)+". Nama    :  " +mOrg.nama.get(i),font2,Element.ALIGN_LEFT);
                    input("    Jabatan :  " +mOrg.jabatan.get(i),font2,Element.ALIGN_LEFT);
                    input("    Tahun    :  " +mOrg.tahunMulai.get(i)+" - "+mOrg.tahunSelesai.get(i),font2,Element.ALIGN_LEFT);
                }
                input(" ",font1,Element.ALIGN_CENTER);
                input("--------------------------------------------------------------------------------------------------------",font2,Element.ALIGN_JUSTIFIED);
                input("PENGALAMAN KEPANITIAAN",font1,Element.ALIGN_CENTER);
                input(" ",font1,Element.ALIGN_CENTER);
                for (int i=0;i<mKep.nama.size();i++) {
                    input((i+1)+". Nama    :  " +mKep.nama.get(i),font2,Element.ALIGN_LEFT);
                    input("    Jabatan :  " +mKep.jabatan.get(i),font2,Element.ALIGN_LEFT);
                    input("    Tahun    :  " +mKep.tahunMulai.get(i)+" - "+mKep.tahunSelesai.get(i),font2,Element.ALIGN_LEFT);
                }
                input(" ",font1,Element.ALIGN_CENTER);
                input("--------------------------------------------------------------------------------------------------------",font2,Element.ALIGN_JUSTIFIED);
                input("RIWAYAT PENDIDIKAN",font1,Element.ALIGN_CENTER);
                input(" ",font1,Element.ALIGN_CENTER);
                for (int i=0;i<mPen.nama.size();i++) {
                    input((i+1)+". " +mPen.nama.get(i),font2,Element.ALIGN_LEFT);
                }
                input(" ",font1,Element.ALIGN_CENTER);
                input("--------------------------------------------------------------------------------------------------------",font2,Element.ALIGN_JUSTIFIED);
                input("RIWAYAT PRESTASI",font1,Element.ALIGN_CENTER);
                input(" ",font1,Element.ALIGN_CENTER);
                for (int i=0;i<mPres.nama.size();i++) {
                    input((i+1)+". " +mPres.nama.get(i),font2,Element.ALIGN_LEFT);
                }
            document.close();
            writer.close();
        } catch(DocumentException e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "File CV_Baru.pdf sukses dibuat di direktori "+loc,"Notification!",HEIGHT);
    }//GEN-LAST:event_jButtonCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLupaPassword;
    private javax.swing.JButton jButtonSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDataTersimpan;
    private javax.swing.JLabel jLabelInstruksi;
    private javax.swing.JLabel jLabelSiapCetak;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
